# Generated by Django 5.2.17 on 2026-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Учебный материал'),
        ),
    ]
