# Generated by Django 5.2.17 on 2026-10-06 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_module_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.module', verbose_name='Модуль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Завершение модуля',
                'verbose_name_plural': 'Завершение модулей',
                'constraints': [models.UniqueConstraint(fields=('user', 'module'), name='unique_user_module_completion')],
            },
        ),
    ]
