# Generated by Django 5.2.17 on 2026-10-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_question_answeroption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Модули адаптации', 'verbose_name_plural': 'Модули адаптации'},
        ),
    ]
