# Generated by Django 5.2.17 on 2026-10-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_alter_answeroption_options_answeroption_is_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulecompletion',
            options={'permissions': [('view_employee_progress', 'Может просматривать прогресс всех сотрудников')], 'verbose_name': 'Завершение модуля', 'verbose_name_plural': 'Завершение модулей'},
        ),
    ]
